package rs.edu.raf.poreskauprava.util;

public enum CategoryType {
    POLJPOPRIVREDNO_ZEMLJISTE_KLASA_1,
    POLJPOPRIVREDNO_ZEMLJISTE_KLASA_2,
    POLJPOPRIVREDNO_ZEMLJISTE_KLASA_3,
    NEPLODNO,
    GRADSKO_GRADJEVINSKO,
    KUCA,
    SUMA
}
